// Generated by CoffeeScript 1.8.0
(function() {
  var fetchPhotos, nconf, util, voteRandom;

  util = require('./util');

  nconf = require('./mynconf');

  fetchPhotos = function(lastEvaluatedKey, done) {
    var params;
    params = {
      TableName: nconf.get('TABLE_PHOTOS'),
      AttributesToGet: ['imageid']
    };
    if (lastEvaluatedKey) {
      params.ExclusiveStartKey = lastEvaluatedKey;
    }
    return util.dynamoDB.scan(params, function(error, data) {
      if (!error) {
        return done(data);
      } else {
        return console.error(error);
      }
    });
  };

  voteRandom = function(data) {
    var params, photo, votes, _i, _len, _ref;
    _ref = data.Items;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      photo = _ref[_i];
      votes = Math.floor((Math.random() * 1000) + 1);
      console.log("Voting " + votes + " on " + photo.imageid);
      params = {
        TableName: nconf.get('TABLE_PHOTOS'),
        Key: {
          imageid: photo.imageid
        },
        AttributeUpdates: {
          votes: {
            Action: 'ADD',
            Value: votes
          }
        }
      };
      util.dynamoDB.updateItem(params, function(error, data) {
        if (error) {
          return console.error(error);
        }
      });
    }
    if (data.LastEvaluatedKey) {
      return fetchPhotos(data.LastEvaluatedKey, voteRandom);
    }
  };

  fetchPhotos(null, voteRandom);

}).call(this);
